
[versions]
jackson-databind = "2.20.1"
lombok = "1.18.42"
slf4j = "2.0.17"
okhttp = "5.3.2"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}